# Generated by Django 3.2.7 on 2021-09-05 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdqttb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quydinhcongty',
            name='tacgia',
        ),
        migrations.RemoveField(
            model_name='quydinhphongban',
            name='phongban',
        ),
        migrations.RemoveField(
            model_name='quydinhphongban',
            name='tacgia',
        ),
        migrations.RemoveField(
            model_name='quytrinh',
            name='tacgia',
        ),
        migrations.RemoveField(
            model_name='quytrinhcongty',
            name='tacgia',
        ),
        migrations.RemoveField(
            model_name='quytrinhphongban',
            name='phongban',
        ),
        migrations.RemoveField(
            model_name='quytrinhphongban',
            name='tacgia',
        ),
        migrations.RemoveField(
            model_name='thongbao',
            name='danhmuc',
        ),
        migrations.RemoveField(
            model_name='thongbao',
            name='phongban',
        ),
        migrations.RemoveField(
            model_name='thongbao',
            name='tacgia',
        ),
        migrations.DeleteModel(
            name='Danhmucthongbao',
        ),
        migrations.DeleteModel(
            name='Quydinhcongty',
        ),
        migrations.DeleteModel(
            name='Quydinhphongban',
        ),
        migrations.DeleteModel(
            name='Quytrinh',
        ),
        migrations.DeleteModel(
            name='Quytrinhcongty',
        ),
        migrations.DeleteModel(
            name='Quytrinhphongban',
        ),
        migrations.DeleteModel(
            name='Thongbao',
        ),
    ]
