# Generated by Django 3.2.1 on 2021-05-22 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loaihopdong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maloaihd', models.CharField(default='', max_length=255, verbose_name='Tên Hợp Đồng')),
                ('tenhd', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Mô Tả Hợp Đồng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LOẠI HỢP ĐỒNG',
                'verbose_name_plural': 'LOẠI HỢP ĐỒNG',
            },
        ),
        migrations.CreateModel(
            name='Nhanvien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manv', models.CharField(default='', max_length=255, unique=True, verbose_name='Mã Nhân Viên')),
                ('tennv', models.CharField(default='', max_length=255, verbose_name='Họ Tên Nhân Viên')),
                ('gioitinh', models.BooleanField(default='', verbose_name='Check - Nếu là nam')),
                ('ngaysinh', models.DateField(verbose_name='Ngày Sinh')),
                ('diachi', models.CharField(default='', max_length=255, verbose_name='Địa chỉ thường trú')),
                ('quequan', models.CharField(default='', max_length=255, verbose_name='Quê Quán')),
                ('cmnd', models.CharField(default='', max_length=12, verbose_name='CCID')),
                ('cmnd_1', models.ImageField(blank=True, default='', null=True, upload_to='img/', verbose_name='Ảnh mặt trước CCID')),
                ('cmnd_2', models.ImageField(blank=True, default='', null=True, upload_to='img/', verbose_name='Ảnh mặt sau CCID')),
                ('avatar', models.ImageField(blank=True, default='', null=True, upload_to='img/', verbose_name='Ảnh chân dung')),
                ('sdt', models.CharField(default='', max_length=255, unique=True, verbose_name='Số Điện Thoại')),
                ('line', models.CharField(default='', max_length=255, verbose_name='Line nội bộ')),
                ('email', models.CharField(blank=True, default='', max_length=255, null=True, unique=True, verbose_name='Email')),
                ('tinhtrangcongviec', models.BooleanField(default='1', verbose_name='Check --- (nếu nhân viên chính thức) ')),
                ('chuky1', models.FileField(blank=True, null=True, upload_to='', verbose_name='Upload chữ ký 1 ')),
                ('chuky2', models.FileField(blank=True, null=True, upload_to='', verbose_name='Upload chữ ký 2 ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NHÂN VIÊN',
                'verbose_name_plural': 'NHÂN VIÊN',
            },
        ),
        migrations.CreateModel(
            name='Phongban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenpb', models.CharField(default='', max_length=255, unique=True, verbose_name='Tên Phòng Ban')),
                ('ngaythanhlap', models.DateTimeField(null=True, verbose_name='Năm thành lập')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'PHÒNG BAN',
                'verbose_name_plural': 'PHÒNG BAN',
            },
        ),
        migrations.CreateModel(
            name='Quatrinhdongbhxh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoigiandong', models.DateTimeField(verbose_name='Ngày-Tháng-Năm Đóng')),
                ('sotiendong', models.CharField(default='', max_length=255, verbose_name='Số Tiền Đóng BHXH')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tennhanvien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlns.nhanvien', verbose_name='Nhân Viên Đóng BHXH')),
            ],
            options={
                'verbose_name': 'QUÁ TRÌNH ĐÓNG BẢO HIỂM XÃ HỘI',
                'verbose_name_plural': 'QUÁ TRÌNH ĐÓNG BẢO HIỂM XÃ HỘI',
            },
        ),
        migrations.CreateModel(
            name='Quanlyhopdongkinhdoanh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masohopdong', models.CharField(default='', max_length=255, unique=True, verbose_name='Mã Số Hợp Đồng')),
                ('tenhopdong', models.CharField(default='', max_length=255, verbose_name='Tên Hợp Đồng')),
                ('khachhang', models.CharField(default='', max_length=255, verbose_name='Tên Khách Hàng')),
                ('ngaytrinhky', models.DateField(default='', max_length=255, verbose_name='Ngày Trình Ký Hợp Đồng')),
                ('filehopdong', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loaihd', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='qlns.loaihopdong', verbose_name='Loại Hợp Đồng')),
                ('nhanvien', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='qlns.nhanvien', verbose_name='Nhân Viên phụ trách')),
            ],
            options={
                'verbose_name': 'QUẢN LÝ HỢP ĐỒNG CÔNG TY',
                'verbose_name_plural': 'QUẢN LÝ HỢP ĐỒNG CÔNG TY',
            },
        ),
        migrations.CreateModel(
            name='Phieuluong_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thang', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('nam', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ngaylamthucte', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('congchuan', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('congthembot', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('luongcoban', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('phucap', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('tiendienthoai', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('tienxang', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('tiencom', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('luongtrachnhiem', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('tiendienthoaihotro', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ngaynghikhongpep', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('truluongnghikhongphep', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('hotrobaohiemtrongluong', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('luoncnx2', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('tongthunhap', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('trutienunggiuathang', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('trutienmatunggiuathang', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('trutiendienthoaicongtytraho', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('trunotrongthang', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('trubaohiem', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('trutienphat', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('truluongluyke', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('tienluongthuclanhcuoithang', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('nothangtruoc', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('muonnothangnay', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('trunotrongluong', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('thunotienmat', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('noconluanchuyensangthangsau', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nhanvien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlns.nhanvien')),
            ],
            options={
                'verbose_name': ' UPLOAD PHIẾU LƯƠNG',
                'verbose_name_plural': 'UPLOAD PHIẾU LƯƠNG',
            },
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='phongban',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='qlns.phongban'),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tài Khoản Nhân Viên'),
        ),
        migrations.CreateModel(
            name='Hosonhanvien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masobh', models.CharField(max_length=255, unique=True, verbose_name='Mã Số HDLD ')),
                ('ngaythuviec', models.DateField(verbose_name='Ngày thử việc')),
                ('ngaychinhthuc', models.DateField(verbose_name='Ngày làm chính thức')),
                ('chuyenmon', models.CharField(default='', max_length=255, verbose_name='Chuyên ngành')),
                ('vanhoa', models.CharField(default='', max_length=255, verbose_name='Trình độ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nhanvien', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='qlns.nhanvien', verbose_name='Họ Tên Nhân Viên')),
            ],
            options={
                'verbose_name': 'HỒ SƠ NHÂN VIÊN',
                'verbose_name_plural': 'HỒ SƠ NHÂN VIÊN',
            },
        ),
        migrations.CreateModel(
            name='Chucvu_Congviec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tencongviec', models.CharField(default='', max_length=255, unique=True, verbose_name='Tên Công việc+ Chúc Vụ')),
                ('motacongviec', models.TextField(verbose_name='Mô tả công việc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nhanvien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlns.nhanvien', verbose_name='Nhân Viên')),
                ('phongban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlns.phongban', verbose_name='Phòng ban')),
            ],
            options={
                'verbose_name': 'NHÂN VIÊN CHỨC VỤ',
                'verbose_name_plural': 'NHÂN VIÊN CHỨC VỤ',
            },
        ),
        migrations.CreateModel(
            name='Baohiemyte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masobhyt', models.CharField(default='', max_length=255, unique=True, verbose_name='Mã Số BHXH')),
                ('ngaythamgia', models.DateField(verbose_name='Ngày tham gia')),
                ('noidangky', models.CharField(default='', max_length=255, verbose_name='Nơi đăng ký BHYT')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nhanvien', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='qlns.nhanvien')),
            ],
            options={
                'verbose_name': 'BẢO HIỂM Y TẾ',
                'verbose_name_plural': 'BẢO HIỂM Y TẾ',
            },
        ),
        migrations.CreateModel(
            name='Baohiemxahoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masobhxh', models.CharField(max_length=255, unique=True, verbose_name='Mã Số BHXH')),
                ('ngaythamgia', models.DateField(verbose_name='Ngày tham gia')),
                ('noidangky', models.CharField(default='', max_length=255, verbose_name='Địa chỉ đăng ký')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nhanvien', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='qlns.nhanvien')),
            ],
            options={
                'verbose_name': 'BẢO HIỂM XÃ HỘI',
                'verbose_name_plural': 'BẢO HIỂM XÃ HỘI',
            },
        ),
    ]
