# Generated by Django 3.2.3 on 2021-07-12 07:49

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dexuat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noidung', ckeditor.fields.RichTextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('guiduyet', models.CharField(choices=[('0', 'Chỉ Gửi Trưởng Phòng'), ('1', 'Gửi Sếp')], max_length=20, verbose_name='Trạng Thái Gửi Duyệt')),
                ('trangthaiduyet_tp', models.BooleanField()),
                ('trangthaiduyet_sep', models.BooleanField()),
                ('tinhtrangxem', models.BooleanField()),
                ('tinhtranghuy', models.BooleanField()),
                ('tientamung', models.IntegerField(default=0)),
                ('ghichu', models.CharField(blank=True, default='(-_-)', max_length=255, null=True)),
                ('thoigianhoanthanh', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nhanvien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlns.nhanvien')),
                ('phongban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlns.phongban')),
            ],
            options={
                'verbose_name': ' ĐỀ XUẤT',
                'verbose_name_plural': 'ĐỀ XUẤT',
            },
        ),
    ]
