# Generated by Django 3.2.3 on 2021-07-13 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0003_auto_20210713_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='dexuat',
            name='tinhtrangtamung',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
