# Generated by Django 3.2.3 on 2021-07-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0004_dexuat_tinhtrangtamung'),
    ]

    operations = [
        migrations.AddField(
            model_name='dexuat',
            name='tieude',
            field=models.CharField(default='', max_length=500),
        ),
    ]
