# Generated by Django 3.2.3 on 2021-07-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0005_dexuat_tieude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dexuat',
            name='ghichu',
            field=models.CharField(blank=True, default='<strong> Nhan vien: </strong>', max_length=255, null=True),
        ),
    ]
