# Generated by Django 3.2.3 on 2021-07-16 07:07

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qlns', '0007_alter_dexuat_ghichu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dexuat',
            name='ghichu',
            field=models.TextField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Giaichi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noidungdexuat', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('noidunggiaichi', ckeditor_uploader.fields.RichTextUploadingField()),
                ('tieude', models.CharField(default='', max_length=500)),
                ('ghichu', models.CharField(default='Thu Quy :', max_length=500)),
                ('filegiaichi', models.FileField(upload_to='')),
                ('trangthaiduyetgiaichi', models.BooleanField()),
                ('trangthaihuy', models.BooleanField()),
                ('trangthaihoanthanh', models.BooleanField()),
                ('tientamung', models.IntegerField(default=0)),
                ('tiengiaichi', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dexuat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlns.dexuat')),
                ('nhanvien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlns.nhanvien')),
                ('phongban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlns.phongban')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GIAI CHI ',
                'verbose_name_plural': 'GIAI CHI',
            },
        ),
    ]
