# Generated by Django 3.2.3 on 2021-07-16 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0008_auto_20210716_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='giaichi',
            name='trangthaiduyet_sep',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='giaichi',
            name='trangthaiduyet_tp',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
