# Generated by Django 3.2.3 on 2021-07-17 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0010_alter_giaichi_noidunggiaichi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giaichi',
            name='noidunggiaichi',
            field=models.JSONField(verbose_name='Nội Dung '),
        ),
    ]
