# Generated by Django 3.2.3 on 2021-07-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0011_alter_giaichi_noidunggiaichi'),
    ]

    operations = [
        migrations.AddField(
            model_name='dexuat',
            name='tinhtranggiaichi',
            field=models.BooleanField(default=False),
        ),
    ]
