# Generated by Django 3.2.3 on 2021-07-18 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0012_dexuat_tinhtranggiaichi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giaichi',
            name='dexuat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qlns.dexuat'),
        ),
    ]
