# Generated by Django 3.2.3 on 2021-07-20 15:39

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0014_alter_chucvu_congviec_tencongviec'),
    ]

    operations = [
        migrations.AddField(
            model_name='giaichi',
            name='hanghoagiaichi',
            field=models.JSONField(blank=True, null=True, verbose_name='Hàng Hóa'),
        ),
        migrations.AlterField(
            model_name='giaichi',
            name='noidunggiaichi',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Hàng Hóa'),
        ),
    ]
