# Generated by Django 3.2.3 on 2021-07-21 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0019_giaichi_hangmuc'),
    ]

    operations = [
        migrations.AddField(
            model_name='giaichi',
            name='guiduyet',
            field=models.CharField(choices=[('0', 'Gửi Sếp'), ('1', ' Chỉ Gửi Trưởng Phòng')], default="", max_length=20, verbose_name='Trạng Thái Gửi Duyệt'),
            preserve_default=False,
        ),
    ]
