# Generated by Django 3.2.3 on 2021-07-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0020_giaichi_guiduyet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giaichi',
            name='filegiaichi',
            field=models.FileField(upload_to='filegiaichi/'),
        ),
    ]
