# Generated by Django 3.2.3 on 2021-07-28 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0021_alter_giaichi_filegiaichi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phanquyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quyenxem', models.BooleanField()),
                ('quyensua', models.BooleanField()),
                ('quyendsp', models.BooleanField()),
                ('quyenxemketoan', models.BooleanField()),
                ('quyensuaketoan', models.BooleanField()),
                ('quyenxemhcns', models.BooleanField()),
                ('quyensuahcns', models.BooleanField()),
                ('quyenxemkho', models.BooleanField()),
                ('quyensuakho', models.BooleanField()),
                ('quyenxempbs', models.BooleanField()),
                ('quyensuapbs', models.BooleanField()),
                ('nhanvien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlns.nhanvien')),
                ('phongban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlns.phongban')),
            ],
            options={
                'verbose_name': 'PHÂN QUYỀN',
                'verbose_name_plural': 'PHÂN QUYỀN',
            },
        ),
    ]
