# Generated by Django 3.2.3 on 2021-07-28 08:02

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0023_phanquyen_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='giaichi',
            name='noidungthanhtoan',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
