# Generated by Django 3.2.3 on 2021-08-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0027_dexuat_nhanviencc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dexuat',
            name='nhanviencc',
            field=models.JSONField(blank=True, max_length=1000, null=True),
        ),
    ]
