# Generated by Django 3.2.7 on 2021-09-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0028_alter_dexuat_nhanviencc'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhanvien',
            name='chuyenmon',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Chuyên ngành'),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='masohs',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Mã Số HDLD '),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='ngaycap',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày Cấp'),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='ngaychinhthuc',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày làm chính thức'),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='ngaythuviec',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày thử việc'),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='noicap',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Nơi Cấp '),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='sdt2',
            field=models.CharField(default='', max_length=255, verbose_name='Số Điện Thoại 2'),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='vanhoa',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Trình độ'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='cmnd',
            field=models.CharField(default='', max_length=12, verbose_name='CMND/CCID'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='cmnd_1',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img/', verbose_name='Ảnh mặt trước CMND/CCID'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='cmnd_2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img/', verbose_name='Ảnh mặt sau CMND/CCID'),
        ),
        migrations.DeleteModel(
            name='Hosonhanvien',
        ),
    ]
