# Generated by Django 3.2.7 on 2021-09-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0029_auto_20210905_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='sdt2',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Số Điện Thoại 2'),
        ),
    ]
