# Generated by Django 3.2.7 on 2021-09-07 04:05

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0032_motacongviec'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kienthucnen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieude', models.CharField(default='', max_length=255, verbose_name='Tiêu Đề Công Việc')),
                ('noidung', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Nội Dung Công Việc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phongban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlns.phongban', verbose_name='Phòng Ban Áp Dụng')),
                ('tacgia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlns.nhanvien', verbose_name='Tác Giả Bài Viết')),
            ],
            options={
                'verbose_name': 'KIẾN THỨC NÉN CHO NHÂN VIÊN ',
                'verbose_name_plural': 'KIẾN THỨC NÉN CHO NHÂN VIÊN ',
            },
        ),
    ]
