# Generated by Django 3.2.7 on 2021-09-07 04:55

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0033_kienthucnen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cauhoithuonggap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cauhoi', models.CharField(default='', max_length=255, verbose_name='Tiêu Đề Công Việc')),
                ('traloi', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Nội Dung Công Việc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CÂU HỎI THƯỜNG GẶP',
                'verbose_name_plural': 'CÂU HỎI THƯỜNG GẶP',
            },
        ),
    ]
