# Generated by Django 3.2.7 on 2021-09-07 10:56

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0034_cauhoithuonggap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cauhoithuonggap',
            name='cauhoi',
            field=models.CharField(default='', max_length=255, verbose_name='Tên Câu Hỏi Thường Gặp'),
        ),
        migrations.AlterField(
            model_name='cauhoithuonggap',
            name='traloi',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Nội Dung Trả lời'),
        ),
        migrations.CreateModel(
            name='Hoidap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cauhoi', models.CharField(default='', max_length=255, verbose_name='Câu Hỏi của Nhân Viên')),
                ('idnhanvienhoi', models.IntegerField()),
                ('nhanvienhoi', models.CharField(default='', max_length=255, verbose_name='Nhân Viên Đặt câu hỏi')),
                ('traloi', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Nội Dung trả lời')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nhanvientraloi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlns.nhanvien', verbose_name='Nhân Viên Trả Lời')),
                ('phongbantraloi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlns.phongban', verbose_name='Phòng Ban Phải Trả Lời')),
            ],
            options={
                'verbose_name': 'HỎI ĐÁP NHÂN VIÊN',
                'verbose_name_plural': 'HỎI ĐÁP NHÂN VIÊN',
            },
        ),
    ]
