# Generated by Django 3.2.7 on 2021-09-07 11:00

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0035_auto_20210907_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoidap',
            name='nhanvientraloi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qlns.nhanvien', verbose_name='Nhân Viên Trả Lời'),
        ),
        migrations.AlterField(
            model_name='hoidap',
            name='traloi',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Nội Dung trả lời'),
        ),
    ]
