# Generated by Django 3.2.7 on 2021-09-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0037_nhanvien_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes/nhanvien/'),
        ),
    ]
