# Generated by Django 3.2.7 on 2021-09-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0038_alter_nhanvien_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quatrinhdongbhxh',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quatrinhdongbhxh',
            name='thoigiandong',
            field=models.DateField(verbose_name='Ngày-Tháng-Năm Đóng'),
        ),
        migrations.AlterField(
            model_name='quatrinhdongbhxh',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
