# Generated by Django 3.2.7 on 2021-09-08 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0040_auto_20210908_2043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quatrinhdongbhxh',
        ),
    ]
