# Generated by Django 3.2.3 on 2021-06-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khovan', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nhapkho',
        ),
    ]
