# Generated by Django 3.2.3 on 2021-06-25 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('khovan', '0002_delete_nhapkho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nhapkho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noidung', models.JSONField()),
                ('tinhtrang_hoanthanh', models.BooleanField(verbose_name='Tình Trạng Hoàn Thành 100% ')),
                ('tinhtrang_treo', models.BooleanField(verbose_name='Tình Trạng Hoàn Thành < 100% ')),
                ('thoigiantao', models.DateField(auto_now_add=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khovan.phieunhaphang', verbose_name='Số Phiếu Nhập Hàng')),
            ],
            options={
                'verbose_name': 'NHẬP KHO ',
                'verbose_name_plural': 'NHẬP KHO',
            },
        ),
    ]
