# Generated by Django 3.2.3 on 2021-07-02 08:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('khovan', '0003_nhapkho'),
    ]

    operations = [
        migrations.AddField(
            model_name='phieunhaphang',
            name='xulykho',
            field=models.BooleanField(default=False, verbose_name='Xu Ly Kho'),
            preserve_default=False,
        ),
    ]
