# Generated by Django 3.2.3 on 2021-08-24 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ngayhoanthanh',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
