# Generated by Django 3.2.3 on 2021-08-24 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_ngayhoanthanh'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='mucdo',
            field=models.CharField(choices=[('0', 'rất gấp'), ('1', 'gấp'), ('2', 'không gấp')], default=django.utils.timezone.now, max_length=20, verbose_name='Mức Độ'),
            preserve_default=False,
        ),
    ]
