# Generated by Django 3.2.7 on 2021-09-08 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qlns', '0038_alter_nhanvien_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhmucCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tendanhmuc', models.CharField(default='', max_length=255, verbose_name='Tên Danh Mục Catalog ')),
                ('motadanhmuc', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Mô Tẩ Danh Mục ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Danh Mục Catalog ',
                'verbose_name_plural': 'Danh Mục Catalog ',
            },
        ),
        migrations.CreateModel(
            name='HangCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenhang', models.CharField(default='', max_length=255, verbose_name='Tên Danh Mục Catalog ')),
                ('motahang', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Mô Tẩ Danh Mục ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hãng Catalog ',
                'verbose_name_plural': 'Hãng Catalog ',
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tencatalog', models.CharField(default='', max_length=255, verbose_name='Tên Catalog ')),
                ('motacatalog', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Tên Catalog (Có Thể bỏ Trống)')),
                ('filecatalog', models.FileField(default='', upload_to='thuvien/file_catalog/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('danhmuccatalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athuvien.danhmuccatalog', verbose_name='Chọn Danh Mục')),
                ('hangcatalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athuvien.hangcatalog', verbose_name='Chọn Hãng ')),
                ('tacgia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlns.nhanvien', verbose_name='Tác Giả ')),
            ],
            options={
                'verbose_name': 'Bài viết Catalog ',
                'verbose_name_plural': 'Bài viết Catalog  ',
            },
        ),
    ]
