# Generated by Django 3.2.7 on 2021-09-08 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athuvien', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='tacgia',
        ),
    ]
