# Generated by Django 3.2.3 on 2021-08-29 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qlns', '0028_alter_dexuat_nhanviencc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tkhd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahopdong', models.CharField(blank=True, default='', max_length=50, null=True, unique=True)),
                ('tieude', models.CharField(default='', max_length=255)),
                ('file', models.FileField(upload_to='filetkhd/')),
                ('ghichu', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('guiduyet', models.CharField(choices=[('0', 'Gửi Anh Thắng'), ('1', ' Chỉ Gửi Trưởng Phòng')], max_length=20, verbose_name='Trạng Thái Gửi Duyệt')),
                ('trangthaiduyet_tp', models.BooleanField()),
                ('trangthaiduyet_at', models.BooleanField()),
                ('trinhtrangduyet_huy', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nhanvien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlns.nhanvien')),
                ('phongban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlns.phongban')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
